server.port=0
grpc.server.port=0

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ewm}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:824322}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=never

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.uuid}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=analyzer
spring.kafka.consumer.auto-offset-reset=earliest

analyzer.kafka.topic.user-actions=stats.user-actions.v1
analyzer.kafka.topic.events-similarity=stats.events-similarity.v1

recommendation.weights.view=0.4
recommendation.weights.register=0.8
recommendation.weights.like=1.0
recommendation.defaults.max-results=10